var gameWords = [
	"THE SHAWSHANK REDEMPTION", "THE GODFATHER", "THE GODFATHER: PART II", "THE DARK KNIGHT",
	"12 ANGRY MEN", "SCHINDLERS LIST", "PULP FICTION", "THE LORD OF THE RINGS: THE RETURN OF THE KING",
	"THE GOOD THE BAD AND THE UGLY", "FIGHT CLUB", "FORREST GUMP", 
	"STAR WARS: EPISODE V - THE EMPIRE STRIKES BACK", "INCEPTION", "THE LORD OF THE RINGS: THE TWO TOWERS",
	"ONE FLEW OVER THE CUCKOO'S NEST", "GOODFELLAS", "THE MATRIX", 
	"SEVEN SAMURAI", "STAR WARS: EPISODE IV - A NEW HOPE", "CITY OF GOD", "SE7EN", 
	"THE SILENCE OF THE LAMBS", "IT'S A WONDERFUL LIFE", "LIFE IS BEAUTIFUL", "THE USUAL SUSPECTS", 
	"LEON: THE PROFESSIONAL", "SPIRITED AWAY", "SAVING PRIVATE RYAN", "INTERSTELLAR", "AMERICAN HISTORY X", 
	"THE GREEN MILE", "ONCE UPON A TIME IN THE WEST", "PSYCHO", "CITY LIGHTS", "CASABLANCA", 
	"THE INTOUCHABLES", "MODERN TIMES", "THE PIANIST", "THE DEPARTED", "RAIDERS OF THE LOST ARK", 
	"TERMINATOR 2", "REAR WINDOW", "BACK TO THE FUTURE", "WHIPLASH", "GLADIATOR", "THE LION KING", 
	"THE PRESTIGE", "MEMENTO", "APOCALYPSE NOW"
];

module.exports = gameWords;